services:
    web:
        container_name: gemini-rag-bot-app
        image: ${DOCKERHUB_USERNAME}/gemini-rag-bot-app:latest
        depends_on:
            - qdrant
            - redis
        networks:
            - app-network
        env_file:
            - .env
        ports:
            - "127.0.0.1:${APP_PORT}:${APP_PORT}"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health"]
            interval: 1m30s
            timeout: 30s
            start_interval: 1m
            start_period: 10s
            retries: 3

    qdrant:
        image: qdrant/qdrant:v1.15
        container_name: gemini-rag-bot-qdrant
        networks:
            - app-network
        volumes:
            - qdrant-storage:/qdrant/storage
        restart: unless-stopped

    redis:
        image: redis:alpine
        container_name: gemini-rag-bot-redis
        command: ["redis-server", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]
        networks:
            - app-network
        volumes:
            - redis-data:/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 1m30s
            timeout: 30s
            start_interval: 1m
            start_period: 10s
            retries: 3
        

networks:
    app-network:
        driver: bridge
        name: gemini-rag-bot-network

volumes:
    redis-data:
        name: gemini-rag-bot-redis-data
    qdrant-storage:
        name: gemini-rag-bot-qdrant-storage