name: Deploy RAG chatbot assistant with VPS

on:
    push:
        branches:
            - production

jobs:
    setup:
        name: Create project folder and environment variable file on VPS
        runs-on: ubuntu-latest
        steps:
            -
                name: Create folder project on VPS
                uses: appleboy/ssh-action@master
                with:
                    username: ${{ secrets.VPS_USERNAME }}
                    host: ${{ secrets.VPS_HOST }}
                    key: ${{ secrets.VPS_KEY }}
                    script: |
                        # Create folder project
                        mkdir -p ${{ secrets.PROJECT_PATH }}
                        cd ${{ secrets.PROJECT_PATH }}
                        
                        # Create environment file if not exists
                        if [ ! -e ".env" ]; then
                            echo "APP_PORT=${{ secrets.APP_PORT }}" >> .env
                            echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
                            echo "SESSION_SECRET_KEY=${{ secrets.APP_SESSION_SECRET_KEY }}" >> .env
                            echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
                            echo "QDRANT_URL=${{ secrets.QDRANT_URL }}" >> .env
                            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env

                            # Set owner and permission for environment file
                            chmod 600 .env
                            chown ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_USERNAME }} .env
                        fi
            - 
                name: Checkout
                uses: actions/checkout@v3
            -
                name: Copy Dockerfile and docker-compose.yml files to VPS
                uses: appleboy/scp-action@master
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USERNAME }}
                    key: ${{ secrets.VPS_KEY }}
                    source: "docker-compose.yml"
                    target: "${{ secrets.PROJECT_PATH }}"

    build-and-push:
        name: Build image and push to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout code
                uses: actions/checkout@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}
            -
                name: Setup QEMU
                uses: docker/setup-qemu-action@v3

            -
                name: Setup Docker Buildx
                uses: docker/setup-buildx-action@v3

            -
                name: Build and push image
                uses: docker/build-push-action@v3
                with:
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/gemini-rag-bot-app:latest
    
    deploy:
        name: Deploy to VPS
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
            -
                name: Deploy to VPS
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USERNAME }}
                    key: ${{ secrets.VPS_KEY }}
                    script: |            
                        # Change to project directory
                        cd ${{ secrets.PROJECT_PATH }}

                        # Login Docker Hub
                        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

                        # Remove old containers and images
                        docker compose down --rmi all 2>/dev/null || true

                        # Run new containers
                        docker compose up -d --build
                        