name: Deploy RAG chatbot assistant with VPS

on:
    push:
        branches:
            - production

jobs:
    build:
        name: Build image and push to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - 
                name: Checkout code
                uses: actions/checkout@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}
            -
                name: Setup QEMU
                uses: docker/setup-qemu-action@v3

            -
                name: Setup Docker Buildx
                uses: docker/setup-buildx-action@v3

            -
                name: Build and push image
                uses: docker/build-push-action@v3
                with:
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/rag-chatbot-assistant-app:latest
    
    deploy:
        name: Deploy to VPS
        needs: build
        runs-on: ubuntu-latest
        steps:
            -
                name: Deploy to VPS
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.VPS_HOST }}
                    username: ${{ secrets.VPS_USERNAME }}
                    key: ${{ secrets.VPS_KEY }}
                    script: |
                        # Create project folder
                        mkdir -p "${{ secrets.PROJECT_PATH }}"
                        cd "${{ secrets.PROJECT_PATH }}"

                        # Remove old container
                        docker stop rag-chatbot-assistant-app 2>/dev/null || true
                        docker rm rag-chatbot-assistant-app 2>/dev/null || true

                        # Remove old image and pull and run new image
                        docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/rag-chatbot-assistant-app:latest
                        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/rag-chatbot-assistant-app:latest


                        # Run new container
                        docker run \
                            -d \
                            --name rag-chatbot-assistant-app \
                            -e PORT=${{ secrets.APP_PORT }} \
                            -e GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
                            -e SESSION_SECRET_KEY=${{ secrets.APP_SESSION_SECRET_KEY }} \
                            -p ${{ secrets.APP_PORT }}:${{ secrets.APP_PORT }} \
                            --restart unless-stopped \
                            your-dockerhub-username/rag-chatbot-assistant-app:latest
                        